markdown: rdiscount
highlighter: pygments
fullurl: 'https://datenschule.de'
url: 'https://datenschule.de'
staticurl: /assets/
exclude:
  - "CNAME"
  - "LICENSE"
  - "browserlist"
  - "Gemfile*"
  - "Readme.md"
  - "*.sh"
  - ".idea/"
  - ".git/"
  - "local/"
  - "scripts/"
  - "_site/"
  - "vendor/"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - octopress-autoprefixer
page_gen:
  - data: cards
    template: card
    name: id
    dir: card
    extension: html
languages: ["de"]
languages_bak: ["de", "en"]
exclude_from_localizations: ["assets", "files", "style", "js", "svg", "fonts", "images", "scripts"]
permalink: blog/:year/:month/:title/
paginate: 8
paginate_path: blog/page/:num/
sass:
  sass_dir: assets/style/_scss
  style: compressed
defaults:
  - scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
      card: true
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
      card: true
collections:
  tutorials:
    output: true
    permalink: /tutorial/:path/