- name: Beedrill
  img:
  mail:
  staff: 0

- name: Charmander
  img:
  mail:
  staff: 0

- name: Pikachu
  img:
  mail:
  staff: 0

- name: Nidorina
  img:
  mail:
  staff: 0

- name: Hypno
  img:
  mail:
  staff: 0

- name: Zapdos
  img:
  mail:
  staff: 0

- name: Mew
  img:
  mail:
  staff: 0
