- name: Beedrill
  img:
  mail:

- name: Charmander
  img:
  mail:

- name: Pikachu
  img:
  mail:

- name: Nidorina
  img:
  mail:

- name: Hypno
  img:
  mail:

- name: Zapdos
  img:
  mail:

- name: Mew
  img:
  mail:
